// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	order "github.com/radiophysiker/d56/internal/domain/order"
	user "github.com/radiophysiker/d56/internal/domain/user"
	mock "github.com/stretchr/testify/mock"

	withdrawal "github.com/radiophysiker/d56/internal/domain/withdrawal"
)

// MockRepositories is an autogenerated mock type for the Repositories type
type MockRepositories struct {
	mock.Mock
}

type MockRepositories_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositories) EXPECT() *MockRepositories_Expecter {
	return &MockRepositories_Expecter{mock: &_m.Mock}
}

// OrderRepository provides a mock function with no fields
func (_m *MockRepositories) OrderRepository() order.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderRepository")
	}

	var r0 order.Repository
	if rf, ok := ret.Get(0).(func() order.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order.Repository)
		}
	}

	return r0
}

// MockRepositories_OrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderRepository'
type MockRepositories_OrderRepository_Call struct {
	*mock.Call
}

// OrderRepository is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) OrderRepository() *MockRepositories_OrderRepository_Call {
	return &MockRepositories_OrderRepository_Call{Call: _e.mock.On("OrderRepository")}
}

func (_c *MockRepositories_OrderRepository_Call) Run(run func()) *MockRepositories_OrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_OrderRepository_Call) Return(_a0 order.Repository) *MockRepositories_OrderRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositories_OrderRepository_Call) RunAndReturn(run func() order.Repository) *MockRepositories_OrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function with no fields
func (_m *MockRepositories) UserRepository() user.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 user.Repository
	if rf, ok := ret.Get(0).(func() user.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.Repository)
		}
	}

	return r0
}

// MockRepositories_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockRepositories_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) UserRepository() *MockRepositories_UserRepository_Call {
	return &MockRepositories_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockRepositories_UserRepository_Call) Run(run func()) *MockRepositories_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_UserRepository_Call) Return(_a0 user.Repository) *MockRepositories_UserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositories_UserRepository_Call) RunAndReturn(run func() user.Repository) *MockRepositories_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawalRepository provides a mock function with no fields
func (_m *MockRepositories) WithdrawalRepository() withdrawal.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithdrawalRepository")
	}

	var r0 withdrawal.Repository
	if rf, ok := ret.Get(0).(func() withdrawal.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(withdrawal.Repository)
		}
	}

	return r0
}

// MockRepositories_WithdrawalRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawalRepository'
type MockRepositories_WithdrawalRepository_Call struct {
	*mock.Call
}

// WithdrawalRepository is a helper method to define mock.On call
func (_e *MockRepositories_Expecter) WithdrawalRepository() *MockRepositories_WithdrawalRepository_Call {
	return &MockRepositories_WithdrawalRepository_Call{Call: _e.mock.On("WithdrawalRepository")}
}

func (_c *MockRepositories_WithdrawalRepository_Call) Run(run func()) *MockRepositories_WithdrawalRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositories_WithdrawalRepository_Call) Return(_a0 withdrawal.Repository) *MockRepositories_WithdrawalRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositories_WithdrawalRepository_Call) RunAndReturn(run func() withdrawal.Repository) *MockRepositories_WithdrawalRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositories creates a new instance of MockRepositories. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositories(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositories {
	mock := &MockRepositories{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
