// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/radiophysiker/d56/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUnitOfWorkFactory is an autogenerated mock type for the UnitOfWorkFactory type
type MockUnitOfWorkFactory struct {
	mock.Mock
}

type MockUnitOfWorkFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWorkFactory) EXPECT() *MockUnitOfWorkFactory_Expecter {
	return &MockUnitOfWorkFactory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx
func (_m *MockUnitOfWorkFactory) Create(ctx context.Context) (domain.UnitOfWork, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.UnitOfWork
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.UnitOfWork, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.UnitOfWork); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.UnitOfWork)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnitOfWorkFactory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUnitOfWorkFactory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWorkFactory_Expecter) Create(ctx interface{}) *MockUnitOfWorkFactory_Create_Call {
	return &MockUnitOfWorkFactory_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockUnitOfWorkFactory_Create_Call) Run(run func(ctx context.Context)) *MockUnitOfWorkFactory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWorkFactory_Create_Call) Return(_a0 domain.UnitOfWork, _a1 error) *MockUnitOfWorkFactory_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnitOfWorkFactory_Create_Call) RunAndReturn(run func(context.Context) (domain.UnitOfWork, error)) *MockUnitOfWorkFactory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWorkFactory creates a new instance of MockUnitOfWorkFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWorkFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWorkFactory {
	mock := &MockUnitOfWorkFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
