// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	order "github.com/radiophysiker/d56/internal/domain/order"

	user "github.com/radiophysiker/d56/internal/domain/user"

	withdrawal "github.com/radiophysiker/d56/internal/domain/withdrawal"
)

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockUnitOfWork) Begin(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockUnitOfWork_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Begin(ctx interface{}) *MockUnitOfWork_Begin_Call {
	return &MockUnitOfWork_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockUnitOfWork_Begin_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) Return(_a0 error) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Begin_Call) RunAndReturn(run func(context.Context) error) *MockUnitOfWork_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockUnitOfWork) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockUnitOfWork_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) Close() *MockUnitOfWork_Close_Call {
	return &MockUnitOfWork_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockUnitOfWork_Close_Call) Run(run func()) *MockUnitOfWork_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_Close_Call) Return(_a0 error) *MockUnitOfWork_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Close_Call) RunAndReturn(run func() error) *MockUnitOfWork_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *MockUnitOfWork) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Commit(ctx interface{}) *MockUnitOfWork_Commit_Call {
	return &MockUnitOfWork_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockUnitOfWork_Commit_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) Return(_a0 error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) RunAndReturn(run func(context.Context) error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// OrderRepository provides a mock function with no fields
func (_m *MockUnitOfWork) OrderRepository() order.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OrderRepository")
	}

	var r0 order.Repository
	if rf, ok := ret.Get(0).(func() order.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order.Repository)
		}
	}

	return r0
}

// MockUnitOfWork_OrderRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderRepository'
type MockUnitOfWork_OrderRepository_Call struct {
	*mock.Call
}

// OrderRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) OrderRepository() *MockUnitOfWork_OrderRepository_Call {
	return &MockUnitOfWork_OrderRepository_Call{Call: _e.mock.On("OrderRepository")}
}

func (_c *MockUnitOfWork_OrderRepository_Call) Run(run func()) *MockUnitOfWork_OrderRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_OrderRepository_Call) Return(_a0 order.Repository) *MockUnitOfWork_OrderRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_OrderRepository_Call) RunAndReturn(run func() order.Repository) *MockUnitOfWork_OrderRepository_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockUnitOfWork) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Rollback(ctx interface{}) *MockUnitOfWork_Rollback_Call {
	return &MockUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) Return(_a0 error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// UserRepository provides a mock function with no fields
func (_m *MockUnitOfWork) UserRepository() user.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserRepository")
	}

	var r0 user.Repository
	if rf, ok := ret.Get(0).(func() user.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.Repository)
		}
	}

	return r0
}

// MockUnitOfWork_UserRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserRepository'
type MockUnitOfWork_UserRepository_Call struct {
	*mock.Call
}

// UserRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) UserRepository() *MockUnitOfWork_UserRepository_Call {
	return &MockUnitOfWork_UserRepository_Call{Call: _e.mock.On("UserRepository")}
}

func (_c *MockUnitOfWork_UserRepository_Call) Run(run func()) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_UserRepository_Call) Return(_a0 user.Repository) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_UserRepository_Call) RunAndReturn(run func() user.Repository) *MockUnitOfWork_UserRepository_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawalRepository provides a mock function with no fields
func (_m *MockUnitOfWork) WithdrawalRepository() withdrawal.Repository {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WithdrawalRepository")
	}

	var r0 withdrawal.Repository
	if rf, ok := ret.Get(0).(func() withdrawal.Repository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(withdrawal.Repository)
		}
	}

	return r0
}

// MockUnitOfWork_WithdrawalRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawalRepository'
type MockUnitOfWork_WithdrawalRepository_Call struct {
	*mock.Call
}

// WithdrawalRepository is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) WithdrawalRepository() *MockUnitOfWork_WithdrawalRepository_Call {
	return &MockUnitOfWork_WithdrawalRepository_Call{Call: _e.mock.On("WithdrawalRepository")}
}

func (_c *MockUnitOfWork_WithdrawalRepository_Call) Run(run func()) *MockUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_WithdrawalRepository_Call) Return(_a0 withdrawal.Repository) *MockUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnitOfWork_WithdrawalRepository_Call) RunAndReturn(run func() withdrawal.Repository) *MockUnitOfWork_WithdrawalRepository_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
