// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransaction is an autogenerated mock type for the Transaction type
type MockTransaction struct {
	mock.Mock
}

type MockTransaction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransaction) EXPECT() *MockTransaction_Expecter {
	return &MockTransaction_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: ctx
func (_m *MockTransaction) Begin(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockTransaction_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransaction_Expecter) Begin(ctx interface{}) *MockTransaction_Begin_Call {
	return &MockTransaction_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *MockTransaction_Begin_Call) Run(run func(ctx context.Context)) *MockTransaction_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransaction_Begin_Call) Return(_a0 error) *MockTransaction_Begin_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Begin_Call) RunAndReturn(run func(context.Context) error) *MockTransaction_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockTransaction) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTransaction_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTransaction_Expecter) Close() *MockTransaction_Close_Call {
	return &MockTransaction_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTransaction_Close_Call) Run(run func()) *MockTransaction_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransaction_Close_Call) Return(_a0 error) *MockTransaction_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Close_Call) RunAndReturn(run func() error) *MockTransaction_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function with given fields: ctx
func (_m *MockTransaction) Commit(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockTransaction_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransaction_Expecter) Commit(ctx interface{}) *MockTransaction_Commit_Call {
	return &MockTransaction_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockTransaction_Commit_Call) Run(run func(ctx context.Context)) *MockTransaction_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransaction_Commit_Call) Return(_a0 error) *MockTransaction_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Commit_Call) RunAndReturn(run func(context.Context) error) *MockTransaction_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function with given fields: ctx
func (_m *MockTransaction) Rollback(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransaction_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockTransaction_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTransaction_Expecter) Rollback(ctx interface{}) *MockTransaction_Rollback_Call {
	return &MockTransaction_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockTransaction_Rollback_Call) Run(run func(ctx context.Context)) *MockTransaction_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTransaction_Rollback_Call) Return(_a0 error) *MockTransaction_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransaction_Rollback_Call) RunAndReturn(run func(context.Context) error) *MockTransaction_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransaction creates a new instance of MockTransaction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransaction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransaction {
	mock := &MockTransaction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
