// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	order "github.com/radiophysiker/d56/internal/domain/order"
	mock "github.com/stretchr/testify/mock"

	user "github.com/radiophysiker/d56/internal/domain/user"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// FindByNumber provides a mock function with given fields: ctx, number
func (_m *MockReader) FindByNumber(ctx context.Context, number string) (*order.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for FindByNumber")
	}

	var r0 *order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*order.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *order.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByNumber'
type MockReader_FindByNumber_Call struct {
	*mock.Call
}

// FindByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *MockReader_Expecter) FindByNumber(ctx interface{}, number interface{}) *MockReader_FindByNumber_Call {
	return &MockReader_FindByNumber_Call{Call: _e.mock.On("FindByNumber", ctx, number)}
}

func (_c *MockReader_FindByNumber_Call) Run(run func(ctx context.Context, number string)) *MockReader_FindByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_FindByNumber_Call) Return(_a0 *order.Order, _a1 error) *MockReader_FindByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByNumber_Call) RunAndReturn(run func(context.Context, string) (*order.Order, error)) *MockReader_FindByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockReader) FindByUserID(ctx context.Context, userID user.UserID) ([]*order.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) ([]*order.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) []*order.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockReader_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.UserID
func (_e *MockReader_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockReader_FindByUserID_Call {
	return &MockReader_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockReader_FindByUserID_Call) Run(run func(ctx context.Context, userID user.UserID)) *MockReader_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.UserID))
	})
	return _c
}

func (_c *MockReader_FindByUserID_Call) Return(_a0 []*order.Order, _a1 error) *MockReader_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByUserID_Call) RunAndReturn(run func(context.Context, user.UserID) ([]*order.Order, error)) *MockReader_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingOrders provides a mock function with given fields: ctx
func (_m *MockReader) FindPendingOrders(ctx context.Context) ([]*order.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingOrders")
	}

	var r0 []*order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*order.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*order.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingOrders'
type MockReader_FindPendingOrders_Call struct {
	*mock.Call
}

// FindPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockReader_Expecter) FindPendingOrders(ctx interface{}) *MockReader_FindPendingOrders_Call {
	return &MockReader_FindPendingOrders_Call{Call: _e.mock.On("FindPendingOrders", ctx)}
}

func (_c *MockReader_FindPendingOrders_Call) Run(run func(ctx context.Context)) *MockReader_FindPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockReader_FindPendingOrders_Call) Return(_a0 []*order.Order, _a1 error) *MockReader_FindPendingOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindPendingOrders_Call) RunAndReturn(run func(context.Context) ([]*order.Order, error)) *MockReader_FindPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
