// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/radiophysiker/d56/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockReader) FindByID(ctx context.Context, id user.UserID) (*user.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) (*user.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) *user.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockReader_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id user.UserID
func (_e *MockReader_Expecter) FindByID(ctx interface{}, id interface{}) *MockReader_FindByID_Call {
	return &MockReader_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockReader_FindByID_Call) Run(run func(ctx context.Context, id user.UserID)) *MockReader_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.UserID))
	})
	return _c
}

func (_c *MockReader_FindByID_Call) Return(_a0 *user.User, _a1 error) *MockReader_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByID_Call) RunAndReturn(run func(context.Context, user.UserID) (*user.User, error)) *MockReader_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLogin provides a mock function with given fields: ctx, login
func (_m *MockReader) FindByLogin(ctx context.Context, login string) (*user.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for FindByLogin")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLogin'
type MockReader_FindByLogin_Call struct {
	*mock.Call
}

// FindByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockReader_Expecter) FindByLogin(ctx interface{}, login interface{}) *MockReader_FindByLogin_Call {
	return &MockReader_FindByLogin_Call{Call: _e.mock.On("FindByLogin", ctx, login)}
}

func (_c *MockReader_FindByLogin_Call) Run(run func(ctx context.Context, login string)) *MockReader_FindByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockReader_FindByLogin_Call) Return(_a0 *user.User, _a1 error) *MockReader_FindByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByLogin_Call) RunAndReturn(run func(context.Context, string) (*user.User, error)) *MockReader_FindByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
