// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordService is an autogenerated mock type for the PasswordService type
type MockPasswordService struct {
	mock.Mock
}

type MockPasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordService) EXPECT() *MockPasswordService_Expecter {
	return &MockPasswordService_Expecter{mock: &_m.Mock}
}

// CheckPassword provides a mock function with given fields: hashedPassword, password
func (_m *MockPasswordService) CheckPassword(hashedPassword string, password string) bool {
	ret := _m.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockPasswordService_CheckPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPassword'
type MockPasswordService_CheckPassword_Call struct {
	*mock.Call
}

// CheckPassword is a helper method to define mock.On call
//   - hashedPassword string
//   - password string
func (_e *MockPasswordService_Expecter) CheckPassword(hashedPassword interface{}, password interface{}) *MockPasswordService_CheckPassword_Call {
	return &MockPasswordService_CheckPassword_Call{Call: _e.mock.On("CheckPassword", hashedPassword, password)}
}

func (_c *MockPasswordService_CheckPassword_Call) Run(run func(hashedPassword string, password string)) *MockPasswordService_CheckPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockPasswordService_CheckPassword_Call) Return(_a0 bool) *MockPasswordService_CheckPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordService_CheckPassword_Call) RunAndReturn(run func(string, string) bool) *MockPasswordService_CheckPassword_Call {
	_c.Call.Return(run)
	return _c
}

// HashPassword provides a mock function with given fields: password
func (_m *MockPasswordService) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockPasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordService_Expecter) HashPassword(password interface{}) *MockPasswordService_HashPassword_Call {
	return &MockPasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockPasswordService_HashPassword_Call) Run(run func(password string)) *MockPasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) Return(_a0 string, _a1 error) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPasswordService_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockPasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordService creates a new instance of MockPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordService {
	mock := &MockPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
