// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/radiophysiker/d56/internal/domain/user"
	mock "github.com/stretchr/testify/mock"

	withdrawal "github.com/radiophysiker/d56/internal/domain/withdrawal"
)

// MockReader is an autogenerated mock type for the Reader type
type MockReader struct {
	mock.Mock
}

type MockReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReader) EXPECT() *MockReader_Expecter {
	return &MockReader_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: ctx, userID
func (_m *MockReader) FindByUserID(ctx context.Context, userID user.UserID) ([]*withdrawal.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 []*withdrawal.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) ([]*withdrawal.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, user.UserID) []*withdrawal.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*withdrawal.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, user.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReader_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockReader_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID user.UserID
func (_e *MockReader_Expecter) FindByUserID(ctx interface{}, userID interface{}) *MockReader_FindByUserID_Call {
	return &MockReader_FindByUserID_Call{Call: _e.mock.On("FindByUserID", ctx, userID)}
}

func (_c *MockReader_FindByUserID_Call) Run(run func(ctx context.Context, userID user.UserID)) *MockReader_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(user.UserID))
	})
	return _c
}

func (_c *MockReader_FindByUserID_Call) Return(_a0 []*withdrawal.Withdrawal, _a1 error) *MockReader_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReader_FindByUserID_Call) RunAndReturn(run func(context.Context, user.UserID) ([]*withdrawal.Withdrawal, error)) *MockReader_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReader creates a new instance of MockReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReader {
	mock := &MockReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
