// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	withdrawal "github.com/radiophysiker/d56/internal/domain/withdrawal"
	mock "github.com/stretchr/testify/mock"
)

// MockWriter is an autogenerated mock type for the Writer type
type MockWriter struct {
	mock.Mock
}

type MockWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWriter) EXPECT() *MockWriter_Expecter {
	return &MockWriter_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, w
func (_m *MockWriter) Save(ctx context.Context, w *withdrawal.Withdrawal) error {
	ret := _m.Called(ctx, w)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *withdrawal.Withdrawal) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWriter_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockWriter_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - w *withdrawal.Withdrawal
func (_e *MockWriter_Expecter) Save(ctx interface{}, w interface{}) *MockWriter_Save_Call {
	return &MockWriter_Save_Call{Call: _e.mock.On("Save", ctx, w)}
}

func (_c *MockWriter_Save_Call) Run(run func(ctx context.Context, w *withdrawal.Withdrawal)) *MockWriter_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*withdrawal.Withdrawal))
	})
	return _c
}

func (_c *MockWriter_Save_Call) Return(_a0 error) *MockWriter_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWriter_Save_Call) RunAndReturn(run func(context.Context, *withdrawal.Withdrawal) error) *MockWriter_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWriter creates a new instance of MockWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWriter {
	mock := &MockWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
